const assert = require('node:assert/strict');
const fs = require('node:fs');
const os = require('node:os');
const path = require('node:path');
const vm = require('node:vm');
const {spawnSync} = require('node:child_process');
const root = path.resolve(__dirname, '..');
const temp = fs.mkdtempSync(path.join(os.tmpdir(), 'talent-project-test-'));
const output = path.join(temp, 'project.json');
const image = path.join(root, 'assets/examples/loop-blue.png');
const args = [path.join(root, 'scripts/new-project.mjs'), image, output];
assert.equal(spawnSync(process.execPath, args).status, 0);
const project = JSON.parse(fs.readFileSync(output));
const context = {window:{}};
vm.runInNewContext(fs.readFileSync(path.join(root, 'editor/render-core.js'), 'utf8'), context);
context.window.TalentSignalRenderer.validateProject(project);
assert.equal(project.layers[0].text, '');
assert.equal(project.layers[1].text, '');
assert.equal(project.layers[2].fontSize, 64);
assert.equal(project.layers[2].visible, false);
assert.deepEqual(Buffer.from(project.background.src.split(',')[1], 'base64'), fs.readFileSync(image));
const first = fs.readFileSync(output);
assert.notEqual(spawnSync(process.execPath, args).status, 0);
assert.deepEqual(fs.readFileSync(output), first);
console.log('PASS: blank text, 64px hidden series, exact embedded background, no overwrite');
