(function () {
  'use strict';
  const R=window.TalentSignalRenderer, $=id=>document.getElementById(id), clone=x=>JSON.parse(JSON.stringify(x));
  const defaults=R.validateProject(window.TALENT_SIGNAL_SEED);
  let project=clone(defaults),image=null,selected='title',crop=false,fontsReady=false,loading=false,measures=[],undo=[],redo=[],merge=null,drag=null,loadRevision=0;
  const canvas=$('preview'),ctx=canvas.getContext('2d'),overlay=$('overlay'),octx=overlay.getContext('2d');
  const fields=['text','fontSize','lineHeight','color','highlight','highlightColor','x','y','width','align','fontWeight','visible','locked'];
  const numeric=new Set(['fontSize','lineHeight','x','y','width','fontWeight']);
  const layer=()=>project.layers.find(l=>l.id===selected);
  function status(message,error=false){$('status').textContent=message;$('status').classList.toggle('error',error);}
  function updateButtons(){ $('undo').disabled=!undo.length||loading;$('redo').disabled=!redo.length||loading;for(const id of ['export-full','export-crop'])$(id).disabled=!fontsReady||!image||loading; }
  function record(key){const now=Date.now();if(!key||!merge||merge.key!==key||now-merge.time>850){undo.push(clone(project));if(undo.length>30)undo.shift();}merge=key?{key,time:now}:null;redo=[];updateButtons();}
  function syncPanel(){const l=layer();for(const name of fields){const input=$(name);if(input.type==='checkbox')input.checked=l[name];else input.value=l[name];}for(const button of document.querySelectorAll('[data-layer]'))button.classList.toggle('active',button.dataset.layer===selected);for(const id of ['scale','focusX','focusY'])$(id).value=project.background[id];$('scale-value').textContent=project.background.scale.toFixed(2)+'×';}
  function render(){measures=R.draw(ctx,project,image);octx.clearRect(0,0,1080,1920);if($('safe').checked){octx.save();octx.fillStyle='rgba(13,30,38,.24)';octx.fillRect(0,0,1080,240);octx.fillRect(0,1680,1080,240);octx.strokeStyle='rgba(255,248,224,.7)';octx.lineWidth=2;octx.setLineDash([12,10]);octx.strokeRect(54,280,972,1360);octx.restore();}const m=measures.find(x=>x.id===selected);if(m){octx.save();octx.strokeStyle='#ffd6a0';octx.lineWidth=3;octx.setLineDash([9,7]);octx.strokeRect(m.box.x-7,m.box.y-7,m.box.width+14,m.box.height+14);octx.restore();}const warnings=R.warnings(project,measures);if(!project.background.src)warnings.unshift('尚未加载背景。上传图片后即可导出封面。');if(!fontsReady)warnings.unshift('字体尚未就绪，当前仅为临时预览。');$('warnings').replaceChildren(...warnings.map(w=>{const p=document.createElement('p');p.textContent='· '+w;return p;}));updateButtons();return measures;}
  function changeField(name){if(loading)return;const input=$(name);let value=input.type==='checkbox'?input.checked:numeric.has(name)?Number(input.value):input.value;if(numeric.has(name)&&(input.value===''||!input.validity.valid))return;const next=clone(project),l=next.layers.find(x=>x.id===selected);l[name]=value;if(name!=='locked')l.locked=true;try{const valid=R.validateProject(next);record(selected+':'+name);project=valid;if(name!=='locked')$('locked').checked=true;render();}catch(err){status(err.message,true);}}
  for(const name of fields)$(name).addEventListener('input',()=>changeField(name));
  for(const button of document.querySelectorAll('[data-layer]'))button.addEventListener('click',()=>{selected=button.dataset.layer;merge=null;syncPanel();render();});
  for(const name of ['scale','focusX','focusY'])$(name).addEventListener('input',()=>{if(loading)return;record('background:'+name);project.background[name]=Number($(name).value);$('scale-value').textContent=project.background.scale.toFixed(2)+'×';render();});
  $('safe').addEventListener('change',render);
  function setRatio(isCrop){crop=isCrop;$('canvas-wrap').classList.toggle('crop',crop);$('full').classList.toggle('active',!crop);$('crop').classList.toggle('active',crop);$('dimensions').textContent=crop?'1080 × 1440 · 中央裁切':'1080 × 1920';render();}
  $('full').addEventListener('click',()=>setRatio(false));$('crop').addEventListener('click',()=>setRatio(true));
  function coords(e){const r=overlay.getBoundingClientRect();return {x:(e.clientX-r.left)*1080/r.width,y:(e.clientY-r.top)*1920/r.height};}
  overlay.addEventListener('pointerdown',e=>{if(loading||e.button!==0)return;const p=coords(e);const hit=[...measures].reverse().find(m=>p.x>=m.box.x-12&&p.x<=m.box.x+m.box.width+12&&p.y>=m.box.y-12&&p.y<=m.box.y+m.box.height+12);if(!hit)return;selected=hit.id;syncPanel();const l=layer();drag={start:p,x:l.x,y:l.y,recorded:false};overlay.setPointerCapture(e.pointerId);overlay.style.cursor='grabbing';render();});
  overlay.addEventListener('pointermove',e=>{if(!drag)return;const p=coords(e);if(!drag.recorded&&Math.hypot(p.x-drag.start.x,p.y-drag.start.y)>2){record();drag.recorded=true;}if(!drag.recorded)return;const l=layer();l.x=Math.round(Math.max(-1080,Math.min(2160,drag.x+p.x-drag.start.x)));l.y=Math.round(Math.max(-1920,Math.min(3840,drag.y+p.y-drag.start.y)));l.locked=true;syncPanel();render();});
  function endDrag(){drag=null;overlay.style.cursor='default';merge=null;}overlay.addEventListener('pointerup',endDrag);overlay.addEventListener('pointercancel',endDrag);overlay.addEventListener('lostpointercapture',endDrag);
  function loadImage(src){if(!src)return Promise.resolve(null);return new Promise((resolve,reject)=>{const img=new Image();const timer=setTimeout(()=>reject(new Error('图片加载超时')),20000);img.onload=()=>{clearTimeout(timer);if(!img.naturalWidth||img.naturalWidth*img.naturalHeight>40000000){reject(new Error('背景尺寸过大，请使用不超过 4000 万像素的图片'));return;}resolve(img);};img.onerror=()=>{clearTimeout(timer);reject(new Error('图片无法解码，请换用有效的 PNG、JPEG 或 WebP'));};img.src=src;});}
  async function setProject(raw, options={}){const valid=R.validateProject(raw);const revision=++loadRevision;loading=true;updateButtons();try{const nextImage=valid.background.src===project.background.src?image:await loadImage(valid.background.src);if(revision!==loadRevision)return false;if(options.history!==false)record();project=valid;image=nextImage;merge=null;syncPanel();status(fontsReady?'项目已载入 · 所有改动只保存在本机':'项目已载入 · 等待字体就绪');return true;}finally{if(revision===loadRevision){loading=false;render();}}}
  async function restore(direction){if(loading)return;const from=direction==='undo'?undo:redo,to=direction==='undo'?redo:undo;if(!from.length)return;const current=clone(project),target=from[from.length-1];try{await setProject(target,{history:false});from.pop();to.push(current);merge=null;updateButtons();}catch(err){status(err.message,true);}}
  $('undo').addEventListener('click',()=>restore('undo'));$('redo').addEventListener('click',()=>restore('redo'));
  function filename(){return (project.name||'Talent-Signal').replace(/[\\/:*?"<>|\x00-\x1f]/g,'-').slice(0,100);}
  function download(blob,name){const list=$('downloads');for(const old of Array.from(list.children)){if(old.download===name){URL.revokeObjectURL(old.href);old.remove();}}const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=name;a.textContent='下载 '+name;list.prepend(a);while(list.children.length>3){const old=list.lastElementChild;URL.revokeObjectURL(old.href);old.remove();}a.click();}
  function save(){download(new Blob([JSON.stringify(project,null,2)],{type:'application/json'}),filename()+'.json');status('项目已准备好 · 若未自动下载，请点下方下载链接');}
  $('save').addEventListener('click',save);$('import').addEventListener('click',()=>$('project-file').click());$('background').addEventListener('click',()=>$('background-file').click());
  $('project-file').addEventListener('change',async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(file.size>48*1024*1024)throw new Error('项目文件超过 48 MB');const raw=JSON.parse(await file.text());await setProject(raw);}catch(err){status('未载入项目：'+err.message+'。当前项目保留。',true);}});
  function readDataURL(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(reader.result);reader.onerror=()=>reject(new Error('无法读取图片'));reader.readAsDataURL(file);});}
  $('background-file').addEventListener('change',async e=>{const file=e.target.files[0];e.target.value='';if(!file)return;try{if(!['image/png','image/jpeg','image/webp'].includes(file.type))throw new Error('请选择 PNG、JPEG 或 WebP 图片');if(file.size>32*1024*1024)throw new Error('图片不能超过 32 MB');const src=await readDataURL(file);const next=clone(project);next.background={src,scale:1,focusX:.5,focusY:.5};await setProject(next);status('背景已替换 · 全部文字设置保留');}catch(err){status('未替换背景：'+err.message,true);}});
  function exportCanvas(ratio='9:16'){if(!fontsReady)throw new Error('字体未就绪，无法导出');if(!image)throw new Error('请先载入背景图');if(loading)throw new Error('项目正在加载');if(!['9:16','3:4'].includes(ratio))throw new Error('导出比例仅支持 9:16 或 3:4');const full=document.createElement('canvas');full.width=1080;full.height=1920;R.draw(full.getContext('2d'),project,image);if(ratio==='9:16')return full;const out=document.createElement('canvas');out.width=1080;out.height=1440;out.getContext('2d').drawImage(full,0,240,1080,1440,0,0,1080,1440);return out;}
  function exportPNG(ratio){try{const out=exportCanvas(ratio);out.toBlob(blob=>{if(!blob){status('PNG 导出失败，请重试',true);return;}download(blob,filename()+'-'+ratio.replace(':','x')+'.png');status('PNG 已生成 · 若未自动下载，请点下方下载链接');},'image/png');}catch(err){status(err.message,true);}}
  $('export-full').addEventListener('click',()=>exportPNG('9:16'));$('export-crop').addEventListener('click',()=>exportPNG('3:4'));
  document.addEventListener('keydown',e=>{if(!(e.metaKey||e.ctrlKey))return;if(e.key.toLowerCase()==='s'){e.preventDefault();save();return;}const editing=e.target.matches('input,textarea,[contenteditable="true"]');if(editing)return;if(e.key.toLowerCase()==='z'){e.preventDefault();restore(e.shiftKey?'redo':'undo');}else if(e.key.toLowerCase()==='y'){e.preventDefault();restore('redo');}});
  function applyAiPatch(patch){if(loading)throw new Error('项目正在加载');if(!patch||!Array.isArray(patch.layers))throw new Error('AI 更新需要 layers 数组');const next=clone(project),skipped=[],updated=[];for(const update of patch.layers){const target=next.layers.find(l=>l.id===update.id);if(!target)throw new Error('未知图层');if(target.locked){skipped.push(target.id);continue;}for(const field of R.editable){if(field!=='locked'&&Object.prototype.hasOwnProperty.call(update,field))target[field]=update[field];}updated.push(target.id);}const valid=R.validateProject(next);if(updated.length){record();project=valid;syncPanel();render();}return {skipped,updated};}
  async function start(){syncPanel();render();let seedError=null,fontError=null;try{if(window.TALENT_SIGNAL_SEED)await setProject(window.TALENT_SIGNAL_SEED,{history:false});}catch(err){seedError=err;}
    try{const fonts=window.TALENT_SIGNAL_FONTS;const covers=(f,weight)=>{const values=String(f.weight).trim().split(/\s+/).map(Number);return f.family==='TS Sans SC'&&(values.length===1?values[0]===weight:values.length===2&&values[0]<=weight&&values[1]>=weight);};if(!Array.isArray(fonts)||!fonts.some(f=>covers(f,400))||!fonts.some(f=>covers(f,900)))throw new Error('缺少本地字体 fonts.js（需要 TS Sans SC 覆盖 400 / 900 字重）');await Promise.all(fonts.map(async f=>{const weights=String(f.weight).trim().split(/\s+/).map(Number);if(typeof f.family!=='string'||!f.family.trim()||weights.length<1||weights.length>2||weights.some(n=>!Number.isFinite(n)||n<1||n>1000)||(weights.length===2&&weights[0]>weights[1]))throw new Error('字体配置不正确');let data;if(typeof f.url==='string'){if(!['fonts/NotoSansSC-Variable.ttf','fonts/Inter-Variable.ttf'].includes(f.url))throw new Error('仅允许随包字体路径');data=f.url;}else{if(typeof f.data!=='string')throw new Error('字体数据无效');data=f.data.startsWith('data:')?f.data:'data:font/woff2;base64,'+f.data;if(!/^data:(font\/[a-z0-9.-]+|application\/octet-stream);base64,[A-Za-z0-9+/=\r\n]+$/i.test(data))throw new Error('字体必须为本地数据');}const face=new FontFace(f.family,'url('+data+')',{weight:String(f.weight),style:'normal'});await face.load();document.fonts.add(face);}));await document.fonts.ready;fontsReady=true;}catch(err){fontError=err;}
    if(fontError)status('字体加载失败：'+fontError.message+'。PNG 导出已停用。',true);else if(seedError)status('初始项目未载入：'+seedError.message,true);else status(image?'已就绪 · 所有编辑和导出仅在本机进行':'字体已就绪 · 请上传背景图');undo=[];redo=[];render();return {fontsReady,seedError:seedError?seedError.message:null,fontError:fontError?fontError.message:null};
  }
  window.coverEditor={getProject:()=>clone(project),setProject,render,exportCanvas,applyAiPatch,ready:null};window.coverEditor.ready=start();
})();
